train_bc: 3
eval_bc: 3
num_epochs: 2000
data_path: /home/wangchangmiao/yuxiao/MRIRecon/mridata/firstMRI/trainImg
eval_path: /home/wangchangmiao/yuxiao/MRIRecon/mridata/firstMRI/trainImg
single_channel: false
mode: double
val_length: 2000
val_inter: 2
save_inter: 4
sample_size: 256
in_channels: 1
out_channels: 1
up_and_down: !!python/tuple
- 128
- 256
- 512
num_res_layers: 2
scaling_factor: 0.18215
vae_resume_path: ''
sd_num_channels: !!python/tuple
- 128
- 256
- 512
- 1024
attention_levels: !!python/tuple
- false
- false
- true
- true
sd_resume_path: ''
controlnet_path: ''
mc_model_path: ''
conditioning_embedding_num_channels: !!python/tuple
- 32
- 96
- 256
diff_loss_coefficient: 0.25
offset_noise: false
mask_path: mask/mask_4.pt
split_batches: false
mixed_precision: fp16
log_with: tensorboard
project_dir: weights/model/sd/exp_6_24
